2025-06-07 00:13:58,402 ERROR: Exception on /index [GET] [in F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\main\routes.py", line 47, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\templates\index.html", line 3, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\templates\base.html", line 80, in top-level template code
    {% block content %}{% endblock %}
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\templates\index.html", line 22, in block 'content'
    {% include '_post.html' %}
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\templates\_post.html", line 8, in top-level template code
    <img src="{{ post.author.avatar(70) }}" class="avatar" />
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\models.py", line 170, in avatar
    return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'
NameError: name 'digest' is not defined
